### ISSUE TITLE
TypeError: '_asyncio.Task' object is not subscriptable

### ISSUE THREAD

**Issue by zsk1993** [elastic/elasticsearch-py-async#54] opened 2018-09-03 08:58 UTC
I want to index the documents with command: ./manage.py search_index --rebuild
the errors as follows:
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "E:\codes\xtsearch\venv\lib\site-packages\django\                                                                                                                                      core\management\__init__.py", line 371, in execute_from_                                                                                                                                      command_line
    utility.execute()
  File "E:\codes\xtsearch\venv\lib\site-packages\django\                                                                                                                                      core\management\__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.ar                                                                                                                                      gv)
  File "E:\codes\xtsearch\venv\lib\site-packages\django\                                                                                                                                      core\management\base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "E:\codes\xtsearch\venv\lib\site-packages\django\                                                                                                                                      core\management\base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "D:\es_test\xtsearch\django_elasticsearch_dsl\man                                                                                                                                      agement\commands\search_index.py", line 134, in handle
    self._rebuild(models, options)
  File "D:\es_test\xtsearch\django_elasticsearch_dsl\man                                                                                                                                      agement\commands\search_index.py", line 115, in _rebuild
    self._populate(models, options)
  File "D:\es_test\xtsearch\django_elasticsearch_dsl\man                                                                                                                                      agement\commands\search_index.py", line 92, in _populate
    doc().update(qs)
  File "D:\es_test\xtsearch\django_elasticsearch_dsl\doc                                                                                                                                      uments.py", line 231, in update
    self._get_actions(object_list, action), **kwargs
  File "D:\es_test\xtsearch\django_elasticsearch_dsl\doc                                                                                                                                      uments.py", line 191, in bulk
    return bulk(client=self.connection, actions=actions,                                                                                                                                       **kwargs)
  File "D:\es_test\xtsearch\elasticsearch\helpers\__init                                                                                                                                      __.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, **kw                                                                                                                                      args):
  File "D:\es_test\xtsearch\elasticsearch\helpers\__init                                                                                                                                      __.py", line 192, in streaming_bulk
    raise_on_error, **kwargs)
  File "D:\es_test\xtsearch\elasticsearch\helpers\__init                                                                                                                                      __.py", line 123, in _process_bulk_chunk
    for data, (op_type, item) in zip(bulk_data, map(meth                                                                                                                                      odcaller('popitem'), resp['items'])):
TypeError: '_asyncio.Task' object is not subscriptable

**Comment by ranjeetkushwaha** [comment] 2019-01-14 12:47
+1

**Comment by fxdgear** [comment] 2019-01-14 16:52
@zsk1993 Thanks for the ticket. 

I'm unfamiliar witht he library `django_elasticsearch_dsl` looking at this library it looks like it's just a wrapper around `elasticsearch_dsl` which is fine. 

though I'm curious if this issue is more a problem in `django_elasticsearch_dsl` and not `elasticsearch_py_async`. 

Can you create something reproducible that does not include Django? Thanks

**Comment by sethmlarson** [comment] 2020-07-20 18:57
Closing as this does not appear to be a defect with this library.

**Closed by sethmlarson** 2020-07-20 18:57 UTC
